CREATE TABLE tblPayment (
    PaymentId int PRIMARY KEY NOT NULL,
    DonatorId int,
    CashAssistanceDetailId int NOT NULL,
    PaymentPrice MONEY NOT NULL,
    PaymentGatewayId VARCHAR(10),
    PaymentDate DATE NOT NULL,
    PaymentTime TIME NOT NULL,
    PaymentStatus NVARCHAR(500) NOT NULL,
    SourceAccountNumber NVARCHAR(10),
    TargetAccountNumber NVARCHAR(10) NOT NULL,
    CharityAccountId int NOT NULL,
    FollowCode VARCHAR(10) NOT NULL,
    NeedyId int,
    CONSTRAINT FK_PaymentDonator FOREIGN KEY (DonatorId) REFERENCES [SabkadV01].[dbo].[tblPersonal](PersonId),
    CONSTRAINT FK_PaymentNeedy FOREIGN KEY (NeedyId) REFERENCES [SabkadV01].[dbo].[tblPersonal](PersonId),
    CONSTRAINT FK_PaymentCashAssistance FOREIGN KEY (CashAssistanceDetailId) REFERENCES [SabkadV01].[dbo].[tblCashAssistanceDetail](CashAssistanceDetailId),
    CONSTRAINT FK_PaymentCharityAccount FOREIGN KEY (CharityAccountId) REFERENCES [SabkadV01].[dbo].[tblCharityAccounts](CharityAccountId),
)